// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: trade_id_mgr.proto

package trade_id_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenTradeIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpId          string                 `protobuf:"bytes,1,opt,name=sp_id,json=spId,proto3" json:"sp_id,omitempty"`        // 商户id
	AccSet        int32                  `protobuf:"varint,2,opt,name=acc_set,json=accSet,proto3" json:"acc_set,omitempty"` // 付款账户所属编号
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`                     // 付款方uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenTradeIdReq) Reset() {
	*x = GenTradeIdReq{}
	mi := &file_trade_id_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenTradeIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTradeIdReq) ProtoMessage() {}

func (x *GenTradeIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_trade_id_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTradeIdReq.ProtoReflect.Descriptor instead.
func (*GenTradeIdReq) Descriptor() ([]byte, []int) {
	return file_trade_id_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *GenTradeIdReq) GetSpId() string {
	if x != nil {
		return x.SpId
	}
	return ""
}

func (x *GenTradeIdReq) GetAccSet() int32 {
	if x != nil {
		return x.AccSet
	}
	return 0
}

func (x *GenTradeIdReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GenTradeIdRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenTradeIdRsp) Reset() {
	*x = GenTradeIdRsp{}
	mi := &file_trade_id_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenTradeIdRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTradeIdRsp) ProtoMessage() {}

func (x *GenTradeIdRsp) ProtoReflect() protoreflect.Message {
	mi := &file_trade_id_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTradeIdRsp.ProtoReflect.Descriptor instead.
func (*GenTradeIdRsp) Descriptor() ([]byte, []int) {
	return file_trade_id_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *GenTradeIdRsp) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

var File_trade_id_mgr_proto protoreflect.FileDescriptor

const file_trade_id_mgr_proto_rawDesc = "" +
	"\n" +
	"\x12trade_id_mgr.proto\x12\ftrade_id_mgr\"O\n" +
	"\rGenTradeIdReq\x12\x13\n" +
	"\x05sp_id\x18\x01 \x01(\tR\x04spId\x12\x17\n" +
	"\aacc_set\x18\x02 \x01(\x05R\x06accSet\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\"*\n" +
	"\rGenTradeIdRsp\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId2T\n" +
	"\n" +
	"TradeIdMgr\x12F\n" +
	"\n" +
	"GenTradeId\x12\x1b.trade_id_mgr.GenTradeIdReq\x1a\x1b.trade_id_mgr.GenTradeIdRspB\x13Z\x11./trade_id_mgr_pbb\x06proto3"

var (
	file_trade_id_mgr_proto_rawDescOnce sync.Once
	file_trade_id_mgr_proto_rawDescData []byte
)

func file_trade_id_mgr_proto_rawDescGZIP() []byte {
	file_trade_id_mgr_proto_rawDescOnce.Do(func() {
		file_trade_id_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_id_mgr_proto_rawDesc), len(file_trade_id_mgr_proto_rawDesc)))
	})
	return file_trade_id_mgr_proto_rawDescData
}

var file_trade_id_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trade_id_mgr_proto_goTypes = []any{
	(*GenTradeIdReq)(nil), // 0: trade_id_mgr.GenTradeIdReq
	(*GenTradeIdRsp)(nil), // 1: trade_id_mgr.GenTradeIdRsp
}
var file_trade_id_mgr_proto_depIdxs = []int32{
	0, // 0: trade_id_mgr.TradeIdMgr.GenTradeId:input_type -> trade_id_mgr.GenTradeIdReq
	1, // 1: trade_id_mgr.TradeIdMgr.GenTradeId:output_type -> trade_id_mgr.GenTradeIdRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_id_mgr_proto_init() }
func file_trade_id_mgr_proto_init() {
	if File_trade_id_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_id_mgr_proto_rawDesc), len(file_trade_id_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_id_mgr_proto_goTypes,
		DependencyIndexes: file_trade_id_mgr_proto_depIdxs,
		MessageInfos:      file_trade_id_mgr_proto_msgTypes,
	}.Build()
	File_trade_id_mgr_proto = out.File
	file_trade_id_mgr_proto_goTypes = nil
	file_trade_id_mgr_proto_depIdxs = nil
}
