// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: trade_id_mgr.proto

package trade_id_mgr_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeIdMgr_GenTradeId_FullMethodName = "/trade_id_mgr.TradeIdMgr/GenTradeId"
	TradeIdMgr_GenUid_FullMethodName     = "/trade_id_mgr.TradeIdMgr/GenUid"
)

// TradeIdMgrClient is the client API for TradeIdMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeIdMgrClient interface {
	GenTradeId(ctx context.Context, in *GenTradeIdReq, opts ...grpc.CallOption) (*GenTradeIdRsp, error)
	GenUid(ctx context.Context, in *GenUidReq, opts ...grpc.CallOption) (*GenUidRsp, error)
}

type tradeIdMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeIdMgrClient(cc grpc.ClientConnInterface) TradeIdMgrClient {
	return &tradeIdMgrClient{cc}
}

func (c *tradeIdMgrClient) GenTradeId(ctx context.Context, in *GenTradeIdReq, opts ...grpc.CallOption) (*GenTradeIdRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenTradeIdRsp)
	err := c.cc.Invoke(ctx, TradeIdMgr_GenTradeId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeIdMgrClient) GenUid(ctx context.Context, in *GenUidReq, opts ...grpc.CallOption) (*GenUidRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenUidRsp)
	err := c.cc.Invoke(ctx, TradeIdMgr_GenUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeIdMgrServer is the server API for TradeIdMgr service.
// All implementations must embed UnimplementedTradeIdMgrServer
// for forward compatibility.
type TradeIdMgrServer interface {
	GenTradeId(context.Context, *GenTradeIdReq) (*GenTradeIdRsp, error)
	GenUid(context.Context, *GenUidReq) (*GenUidRsp, error)
	mustEmbedUnimplementedTradeIdMgrServer()
}

// UnimplementedTradeIdMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeIdMgrServer struct{}

func (UnimplementedTradeIdMgrServer) GenTradeId(context.Context, *GenTradeIdReq) (*GenTradeIdRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenTradeId not implemented")
}
func (UnimplementedTradeIdMgrServer) GenUid(context.Context, *GenUidReq) (*GenUidRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenUid not implemented")
}
func (UnimplementedTradeIdMgrServer) mustEmbedUnimplementedTradeIdMgrServer() {}
func (UnimplementedTradeIdMgrServer) testEmbeddedByValue()                    {}

// UnsafeTradeIdMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeIdMgrServer will
// result in compilation errors.
type UnsafeTradeIdMgrServer interface {
	mustEmbedUnimplementedTradeIdMgrServer()
}

func RegisterTradeIdMgrServer(s grpc.ServiceRegistrar, srv TradeIdMgrServer) {
	// If the following call panics, it indicates UnimplementedTradeIdMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeIdMgr_ServiceDesc, srv)
}

func _TradeIdMgr_GenTradeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenTradeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeIdMgrServer).GenTradeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeIdMgr_GenTradeId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeIdMgrServer).GenTradeId(ctx, req.(*GenTradeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeIdMgr_GenUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenUidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeIdMgrServer).GenUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeIdMgr_GenUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeIdMgrServer).GenUid(ctx, req.(*GenUidReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeIdMgr_ServiceDesc is the grpc.ServiceDesc for TradeIdMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeIdMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade_id_mgr.TradeIdMgr",
	HandlerType: (*TradeIdMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenTradeId",
			Handler:    _TradeIdMgr_GenTradeId_Handler,
		},
		{
			MethodName: "GenUid",
			Handler:    _TradeIdMgr_GenUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_id_mgr.proto",
}
