// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_id_mgr.proto

package server

import (
	"context"

	"github.com/starslipay/trade_id_mgr/internal/logic"
	"github.com/starslipay/trade_id_mgr/internal/svc"
	"github.com/starslipay/trade_id_mgr/trade_id_mgr_pb"
)

type TradeIdMgrServer struct {
	svcCtx *svc.ServiceContext
	trade_id_mgr_pb.UnimplementedTradeIdMgrServer
}

func NewTradeIdMgrServer(svcCtx *svc.ServiceContext) *TradeIdMgrServer {
	return &TradeIdMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeIdMgrServer) GenTradeId(ctx context.Context, in *trade_id_mgr_pb.GenTradeIdReq) (*trade_id_mgr_pb.GenTradeIdRsp, error) {
	l := logic.NewGenTradeIdLogic(ctx, s.svcCtx)
	return l.GenTradeId(in)
}

func (s *TradeIdMgrServer) GenUid(ctx context.Context, in *trade_id_mgr_pb.GenUidReq) (*trade_id_mgr_pb.GenUidRsp, error) {
	l := logic.NewGenUidLogic(ctx, s.svcCtx)
	return l.GenUid(in)
}
