// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: trade_id_mgr.proto

package tradeidmgr

import (
	"context"

	"github.com/starslipay/trade_id_mgr/trade_id_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenTradeIdReq = trade_id_mgr_pb.GenTradeIdReq
	GenTradeIdRsp = trade_id_mgr_pb.GenTradeIdRsp

	TradeIdMgr interface {
		GenTradeId(ctx context.Context, in *GenTradeIdReq, opts ...grpc.CallOption) (*GenTradeIdRsp, error)
	}

	defaultTradeIdMgr struct {
		cli zrpc.Client
	}
)

func NewTradeIdMgr(cli zrpc.Client) TradeIdMgr {
	return &defaultTradeIdMgr{
		cli: cli,
	}
}

func (m *defaultTradeIdMgr) GenTradeId(ctx context.Context, in *GenTradeIdReq, opts ...grpc.CallOption) (*GenTradeIdRsp, error) {
	client := trade_id_mgr_pb.NewTradeIdMgrClient(m.cli.Conn())
	return client.GenTradeId(ctx, in, opts...)
}
