// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tIdSegmentFieldNames          = builder.RawFieldNames(&TIdSegment{})
	tIdSegmentRows                = strings.Join(tIdSegmentFieldNames, ",")
	tIdSegmentRowsExpectAutoSet   = strings.Join(stringx.Remove(tIdSegmentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tIdSegmentRowsWithPlaceHolder = strings.Join(stringx.Remove(tIdSegmentFieldNames, "`scene_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tIdSegmentModel interface {
		Insert(ctx context.Context, data *TIdSegment) (sql.Result, error)
		FindOne(ctx context.Context, sceneId int64) (*TIdSegment, error)
		Update(ctx context.Context, data *TIdSegment) error
		Delete(ctx context.Context, sceneId int64) error
	}

	defaultTIdSegmentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TIdSegment struct {
		SceneId        int64     `db:"scene_id"`         // 场景标识
		MaxAllocatedId int64     `db:"max_allocated_id"` // 当前已分配出去的最大ID
		MinId          int64     `db:"min_id"`           // 最小ID用于隔离不同业务池的ID范围
		MaxId          int64     `db:"max_id"`           // 最大ID用于隔离不同业务池的ID范围
		StepSize       int64     `db:"step_size"`        // 每次批量领取号段步长
		Memo           string    `db:"memo"`             // 备注
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
	}
)

func newTIdSegmentModel(conn sqlx.SqlConn) *defaultTIdSegmentModel {
	return &defaultTIdSegmentModel{
		conn:  conn,
		table: "`t_id_segment`",
	}
}

func (m *defaultTIdSegmentModel) Delete(ctx context.Context, sceneId int64) error {
	query := fmt.Sprintf("delete from %s where `scene_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, sceneId)
	return err
}

func (m *defaultTIdSegmentModel) FindOne(ctx context.Context, sceneId int64) (*TIdSegment, error) {
	query := fmt.Sprintf("select %s from %s where `scene_id` = ? limit 1", tIdSegmentRows, m.table)
	var resp TIdSegment
	err := m.conn.QueryRowCtx(ctx, &resp, query, sceneId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTIdSegmentModel) Insert(ctx context.Context, data *TIdSegment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tIdSegmentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SceneId, data.MaxAllocatedId, data.MinId, data.MaxId, data.StepSize, data.Memo)
	return ret, err
}

func (m *defaultTIdSegmentModel) Update(ctx context.Context, data *TIdSegment) error {
	query := fmt.Sprintf("update %s set %s where `scene_id` = ?", m.table, tIdSegmentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MaxAllocatedId, data.MinId, data.MaxId, data.StepSize, data.Memo, data.SceneId)
	return err
}

func (m *defaultTIdSegmentModel) tableName() string {
	return m.table
}
